### PR TITLE
adds three availability zones support

### PR DESCRIPTION
**Pull request by vicinus**
Adds support to use three availability zones to spread nodes across.

### CODE REVIEW

**Comment by vicinus** [comment]
I can fix the yamllint checks, but there are so many in the original code, that I was not sure if that would have been a good idea.

**Comment by michaelwittig** [comment]
hi @vicinus 

your change contains breaking changes.  Is it possible to avoid them?

**Comment by vicinus** [comment]
Sorry, regarding the yamllint  issue. Was the only breaking change the parameter name change or are there other breaking changes?

**Comment by michaelwittig** [comment]
closing because of age

**Pull request closed without merging**
