### PR TITLE
added lambda file

### PR DESCRIPTION
**Pull request by hary473**
**(Override all values in parentheses)**

(Run `yamllint folder/template.yaml`, `cfn-lint -i E1019 E3002 E2520 -t folder/template.yaml`, and `aws cloudformation validate-template --template-body file://folder/template.yaml` before you open a PR)

(Do not include multiple changes in one PR. Open additional PRs instead.)

---

(describe your change here)

### CODE REVIEW

**Comment by hary473** [comment]
checked

**Comment by michaelwittig** [comment]
@hary473 is this PR on purpose?

**Comment by hary473** [comment]
Sorry it was by mistake .

**Comment by hary473** [comment]
Got it, thanks!

**Pull request closed without merging**
