### PR TITLE
Stack to add flowlogs to VPC.

### PR DESCRIPTION
**Pull request by statik**
This is a simple stack that builds on the VPC stack and adds network flow logs.

### CODE REVIEW

**Comment by michaelwittig** [comment]
I will make some changes to your template and rename the names of the resources. Otherwise you can only have one stack of this template in an account/region.

**Comment by statik** [comment]
Thanks!

**Comment by michaelwittig** [comment]
I also added your GitHub Profile to the top of the template to make it more clear who contributed the template. let me know if this is fine for you.

**Comment by statik** [comment]
Sure, sounds good. Thanks for improving it!

**Pull request merged**
