### PR TITLE
ECS: move lambda to YAML template

### PR DESCRIPTION
**Pull request by homeyjd**
Your PR guidelines request smaller changes, so I'm splitting this up into "stages".  This is PR 3 of 3. (1: #294, 2: #295) . Recommendation would be to skip #294 and #295 and merge this one!

Perform PR #294 _and_ #295 _and_ ...

- The `lifecycle-poller` Ruby scripts took up about ~160 lines of code and were included in the YAML template.  The JavaScript version is ~100 lines of code.  The current implementation requires constant releases via S3 and additional infrastructure.  Seems easier to simply include the code within the YAML template again.  

Lambda layers are certainly a cool new feature, but wouldn't it make more sense to keep the upgrade/release process similar to other aws-cf-templates and just run a CloudFormation update?

### CODE REVIEW

**Comment by michaelwittig** [comment]
We only have 4096 chars available in Lambda inline code. That's not going to work.

**Comment by homeyjd** [comment]
Current version on this branch is 3743 characters.  Just sayin' ...

**Comment by michaelwittig** [comment]
Let't wait for @andreaswittig as far as I understand the layer workaround was introduced because the code was larger than what is allowed.

**Comment by andreaswittig** [comment]
I'm not a huge fan of Lambda Layers. But my editor is counting 4771 characters for `lib.js`. Inline functions are limited to 4096 characters.

We discussed the following options:

1. Use the CLI with `aws cloudformation package` and `aws cloudformation deploy`. But when doing so the template is no longer usable from the Management Console. We assume that a lot of people are using our templates from the Management Console. Similar problem with CI/CD pipelines.
1. Minify the JavaScript code. But doing so makes it hard to read and debug the code within the template.
1. Using a Lambda layer. Code is easy to read and debug. Templates can be used from the Management Console. Downside you have to trust our published Lambda layers.

**Comment by homeyjd** [comment]
@andreaswittig I can only get a character-count of over 4000 if I am counting the space-indent characters _within the YAML template_.  Copy the file into an editor and remove the indents -- should easily be under 4000.  

If still unconvinced, I've got plenty of character-saving ideas if you need them ;).

**Comment by michaelwittig** [comment]
I inlined the code in #297 which is now slightly under the 4096 chars limit. I hope this will not bite us in the future :)

**Pull request closed without merging**
