### PR TITLE
ECS improvements

### PR DESCRIPTION
**Pull request by michaelwittig**

### CODE REVIEW

**Comment by ScottBrenner** [comment]
Any plans to add support for [`DockerVolumeConfiguration`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-taskdefinition-dockervolumeconfiguration.html) or [`RepositoryCredentials`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-taskdefinition-repositorycredentials.html)?

**Comment by andreaswittig** [comment]
@ScottBrenner could you please describe your use case for volume drivers and repository credentials in detail?

**Comment by ScottBrenner** [comment]
My specific use case:

- Using the ECS templates here, I'd like to run [a Docker container](https://github.com/stevearc/pypicloud-docker) that uses volume mounts to pass a configuration file to the container. I can't currently do this, since volume mounts are not supported.
- Instead of mounting the configuration file I could instead build it into the image - in this case I would want to store the Docker image in my own/private Docker registry. I can't currently do this, since I cannot provide "private repository credentials" to pull the image with.

**Comment by ScottBrenner** [comment]
Still hoping for [`DockerVolumeConfiguration`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-taskdefinition-dockervolumeconfiguration.html) or [`RepositoryCredentials`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-taskdefinition-repositorycredentials.html) support 😁

**Comment by michaelwittig** [comment]
@ScottBrenner I suggest you open an issue with your feature request. We are not tracking the contents of a closed PR.
Besides that, feel free to submit a PR that implements your feature request

**Pull request closed without merging**
