### PR TITLE
Create VPC_with_OpenSwan_VPN

### PR DESCRIPTION
**Pull request by valencetech**
Cloudformation template to create a VPC with OpenSwan VPN Server. 
Still under development, thanks for your review.

### CODE REVIEW

**Comment by andreaswittig** [comment]
Hi @valencetech, thanks for your PR. Your idea is to setup a VPN server that allows to connect from anywhere to a VPC, isn't it?

We are usually splitting the VPC/networking configuration into a separate template (see https://github.com/widdix/aws-cf-templates/tree/master/vpc). This allows to combine different templates within a single VPC, for example.

**Comment by michaelwittig** [comment]
Hi,
as Andreas said, could you separate the VPC like we do in the rest of the templates.

Also:
* All our templates are in YAML, could you convert?
* we prefer to have no single point of failures, so please put the EC2 instances inside an Auto Scaling group like we did e.g. in the NAT instance template. This will ensure that a new instance is created if the instance fails for some reasons. https://github.com/widdix/aws-cf-templates/blob/master/vpc/vpc-nat-instance.yaml
* some parts of the template can be found using Google, if you copy, please credit and make sure that the license is compatible with the Apache 2 license we use in this project

If you need more details let me know.

**Comment by valencetech** [comment]
Hi @andreaswittig and @michaelwittig ,

Thanks for the suggestions, I will make the recommended changes.

**Comment by valencetech** [comment]
Hi Michael,

Thanks, I'll convert it to yaml format and remove VPC configuration.

Best regards
Olumide

Get Outlook for Android<https://aka.ms/ghei36>


________________________________

**Pull request closed without merging**
