### PR TITLE
 [Improvement] jenkins/* - Update Jenkins to 2.164.1

### PR DESCRIPTION
**Pull request by michaelwittig**

### CODE REVIEW

**Comment by michaelwittig** [comment]
It looks like AWS messed things up with the ruby sdk... If we wait for the fix we can revert the upgrade to ruby 2.4 https://github.com/aws/aws-sdk-ruby/issues/1994

In the meantime: This PR is tested. You can use is if you need a working setup in the meantime.

**Comment by Ten0** [comment]
With AgentMinSize set to 1, my agents get killed every 12 minutes with the following error :
`an instance was taken out of service in response to a ELB system health check failure.` (health check grace = 600 + two healthchecks -60s each- probably).
Can you reproduce ?

**Comment by michaelwittig** [comment]
No, I can not reproduce it. Can you double check that your template is this: https://github.com/widdix/aws-cf-templates/blob/c1510cb389cc4f8d3a511d55400d72ac07f18b6a/jenkins/jenkins2-ha-agents.yaml

**Comment by michaelwittig** [comment]
AWS has fixed the bug in the Ruby SDK. We don't need ruby > 2.1 any longer

**Comment by michaelwittig** [comment]
see #289

**Pull request closed without merging**
