### PR TITLE
Set logretention for Lambda LogGroup

### PR DESCRIPTION
**Pull request by sgzijl**
**(Override all values in parentheses)**

(Run `yamllint folder/template.yaml` and `aws cloudformation validate-template --template-body file://folder/template.yaml` before you open a PR)

(Do not include multiple changes in one PR. Open additional PRs instead.)

---

Hi there,

Adding log retention for the log group that is used by the Lambda lifecycle function.

This change might break updating the existing CloudFormation stack, because the log group is already created by a previous CloudFormation run. 

Decided to set the `DeletionPolicy` to `Retain`, so that log retention stays there if a stack is deleted (_CF's default behaviour is setting `Expire Events After` to `Never expire`_ ).

Greetz, Siert

### CODE REVIEW

**Comment by michaelwittig** [comment]
Hi @sgzijl 

as you said, this will not work for existing clusters and that's the reason why we can't implement it like this. The users of the templates always need to have a way to update to the next version. To fix this, you could just change the Logical if of the Lambda resource and we should be fine :)

Additonally, instead of:

```
!Join ['', [/aws/lambda/, !Ref 'SchedulableContainersLambda']]
````

you could use:

```
!Sub '/aws/lambda${SchedulableContainersLambda}'
```

which is cleaner/shorther.

**Comment by sgzijl** [comment]
Hello Michael,

Ok, clear 👍 

There is no other way of getting this implemented without breaking things as far as I can think of now.

Thanks for the response. For now I'll close the PR.

**Comment by michaelwittig** [comment]
huh? I beleieve there is a way @sgzijl By renaming the logic id of the Lambda function from `SchedulableContainersLambda`to e.g. `SchedulableContainersLambdaV2` CFN will create a new lambda function and therefore the log group can be created as well?

**Comment by michaelwittig** [comment]
And I would like to see this change because it improves the templates :) Do you min reopening the PR?

**Comment by sgzijl** [comment]
No, I don't mind and re-opened the pr. Did the rename action locally and going to test it right away. I'll come back to you soon with an update.

**Comment by sgzijl** [comment]
@michaelwittig - Did the rename action, created the original stack and applied the update. Thinks don't break and seem to work as expected. Please review and merge.

**Comment by michaelwittig** [comment]
Thanks @sgzijl

**Pull request merged**
