### PR TITLE
Increase password length to match API tokens

### PR DESCRIPTION
**Pull request by ab77**
When Jenkins is configured for another authentication provider (i.e. SAML), the existing admin login is invalidated. To work around this, an API token can be generated for the admin user. These tokens are 34 characters in length by default. It would be useful to be able to re-roll the stack to update the password in all of the scripts under this use-case.

**(Override all values in parentheses)**

(Run `yamllint folder/template.yaml`, `cfn-lint -i E1019 E3002 E2520 -t folder/template.yaml`, and `aws cloudformation validate-template --template-body file://folder/template.yaml` before you open a PR)

(Do not include multiple changes in one PR. Open additional PRs instead.)

---

When Jenkins is configured for another authentication provider (i.e. SAML), the existing admin login is invalidated. To work around this, an API token can be generated for the admin user. These tokens are 34 characters in length by default. It would be useful to be able to re-roll the stack to update the password in all of the scripts under this use-case.

### CODE REVIEW

**Comment by michaelwittig** [comment]
As far as I can remember the Max length of 32 is important for password. Can you validate that a regular user with a password of 34 characters work?

**Comment by ab77** [comment]
Yep, I've tested it on v2.138.3 and it seems to be working.

**Comment by michaelwittig** [comment]
Hi @ab77 We are both attending [re:Invent](https://reinvent.awsevents.com/) this week. Please bear with our longer response times than usual.

**Comment by ab77** [comment]
No rush, enjoy Vegas! 😬

**Comment by ab77** [comment]
Closing due to inaction - pull from `ab77/aws-cf-templates` for latest changes.

**Pull request closed without merging**
